name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish OpenExchangeRatesSharp
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: alirezanet/publish-nuget@v3.1.0
      with:
          PROJECT_FILE_PATH: OpenExchangeRatesSharp/OpenExchangeRatesSharp.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
